repos:
  - repo: https://github.com/psf/black
    rev: main

    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/pycqa/flake8
    rev: main

    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: main

    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: main

    hooks:
      - id: pylint

  - repo: https://github.com/PyCQA/isort
    rev: main

    hooks:
      - id: isort
